name: play-1984 # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Just trying out things to get a feel for it # 79 char long summary
description: |
  Just trying out things to get a feel for it

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
architectures:
  - amd64

apps:
  play-1984: # This app name is arbitrary, but it's better if it matches the snap name.
    command: bin/hello # This command has to match the command coming out of the part build.

parts:
# ===========================================================================
# Part from source looks like this:
#
#  gnu-hello:
#    source: http://ftp.gnu.org/gnu/hello/hello-2.10.tar.gz
#    plugin: autotools
#
# I guess a part-from-source always creates the binary in bin/<part>?
# =========================================================================== 
  deb-hello:
    plugin: nil
    organize:
      usr/bin/hello: bin/hello # L side -> path in package, R side -> desired path in snap.
    stage-packages:
      - hello
