name: play-1984 # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Just trying out things to get a feel for it # 79 char long summary
description: |
  Just trying out things to get a feel for it

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
architectures:
  - amd64

apps:
  play-1984:
    command: usr/bin/hello

parts:
#  gnu-hello:
#    source: http://ftp.gnu.org/gnu/hello/hello-2.10.tar.gz
#    plugin: autotools
  hello:
    plugin: nil
    stage-packages:
      - hello
